name: Commit validation

on:
  [ pull_request ]

jobs:
  commitsar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Commitsar Action
        uses: aevea/commitsar@v0.20.2
